### ISSUE TITLE
Xaml Storyboard.Resume broken in 14393 and later

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#182] opened 2016-11-30 09:55 UTC
`Storyboard.Resume` doesn't work in SDK _14393_ and _14965_. However, it works perfectly in _10586_.

**Comment by JasterAtMicrosoft** [comment] 2016-11-30 18:01
Just to make sure we're on the same page, can you please attach a project that reproduces this problem?

Thanks,
Jake

**Comment by JustinXinLiu** [comment] 2016-11-30 21:11
[Here](https://github.com/JustinXinLiu/StoryboardResumeBrokenRepo) you go. If you change the **Target version** of the project to _10586_ and you will see the animation resumes smoothly.

**Comment by JasterAtMicrosoft** [comment] 2016-12-13 00:35
Thanks for the info Justin! I assume you're talking about the slight "jump" when you call Resume() in the 14393+? This is almost definitely an artifact of some architectural changes we made in our animations stack but it's something we can look into improving.

Are you using Storyboard.Pause and Storyboard.Resume in in app?

**Comment by JustinXinLiu** [comment] 2016-12-13 00:39
Not slight "jump" at all. Once the end time reaches, the element simply goes to the end state immediately. Please have a look at the repo I attached.

> [Here](https://github.com/JustinXinLiu/StoryboardResumeBrokenRepo) you go. If you change the Target version of the project to 10586, you will see the animation resumes smoothly.

**Comment by JasterAtMicrosoft** [comment] 2016-12-13 01:20
Thanks Justin! I'm not seeing that behavior on my internal build, and it looks like we addressed the problem in a recent code change. So, the fix should be available in insider preview builds in the future. In the meantime I'm going to close this issue, but please reopen if this is blocking you or you need assistance with a workaround.

Thanks,
Jake

**Closed by JasterAtMicrosoft** 2016-12-13 01:20 UTC
Labels: bug
