### ISSUE TITLE
Known Issue: Memory leak in image loading when applying ArithmeticCompositeEffect

### ISSUE THREAD

**Issue by cyrilcathala** [Microsoft/WindowsUIDevLabs#24] opened 2016-03-04 15:47 UTC
Hi,

I have implemented an ArithmeticCompositeEffect in my app which I apply every 20s to animate a blend between 2 images. I can see memory grow steadily... 

I have extract a sample project for you to have a look: https://github.com/cyrilcathala/CompositionBlendEffect

Do you have any best practices about memory management, and when to dispose what?

Thanks!

**Comment by pgills** [comment] 2016-03-04 17:46
@cyrilcathala Thanks for the reduced repo. This is super helpful.

We've been seeing some issues with the image loader helper. Which is what we can believe is the root cause. But we'll get someone to investigate to verify.

We're working on update for more efficient ways for uploading image data. So stay tuned for that.

**Comment by cyrilcathala** [comment] 2016-03-04 18:02
Great news, and thanks for the quick reply!

Do you have any timeline to share for the update? 
I'd like to publish a new app, and that's quite the last piece of the puzzle to solve...

**Comment by pgills** [comment] 2016-03-04 18:54
@cyrilcathala Unfortunately, we can't share out direct timelines (which doesn't help you), but we are actively working on it. 

However there are some possible workarounds to unblock you in the very near term, note things can change though.

A DIY more flexible, but more complex version:
- Leverage `Win2D` + `Windows.UI.Composition` interop
 - Load the image data using [CanvasBtimap](http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_CanvasBitmap.htm) from `Win2D`
 - Use Win2D to draw the image data on a `CompositionDrawingSurface` using the [Win2D CompositionExample](https://github.com/Microsoft/Win2D-Samples/blob/master/CompositionExample/UAP/DrawingSurfaceRenderer.cs)
 - Use that `CompositionDrawingSurface` to create a `SurfaceBrush` and use that as input to your `Effect`

This gives you super flexibility in terms of you can use Win2D to draw effects directly to the image data(these aren't animated by the Compositor at runtime), and then use that as input to an Effect that you want to animate with the Compositor at runtime. 

Like I said more flexible, but a little more complex.

@robmikh has been experimenting in this area and you can have a look at what he's being doing here:
(https://github.com/robmikh/compositionimageloader).

Hope that helps for the relatively short term.

By the way, what build(s) are you looking to target and are you on the Windows Insider program?

**Comment by cyrilcathala** [comment] 2016-03-04 19:16
Ok great, now I have what I need, thanks for the detailed answer, really appreciate.
I'll definitively have a look at @robmikh project.

Can't wait to see what's next with those awesome APIs :)

**Comment by cyrilcathala** [comment] 2016-03-04 20:10
Just to let you know, I am now using the CompositionImageLoader, and it is a winner! No more memory leaks, I'm thrilled! :)

Thanks again @pgills, I close the issue.

**Comment by pgills** [comment] 2016-03-04 20:23
@cyrilcathala Thanks! I'm going to keep this issue open for a little bit longer incase other folks run into this so they have a temporary work around, until publish our update.

**Comment by pgills** [comment] 2016-04-12 17:57
Closing. We have an updated ImageLoader in the Samples Common project file. Recommending moving to that implementation.

**Closed by pgills** 2016-04-12 17:57 UTC
Labels: bug
