### ISSUE TITLE
HostBackDrop runs into an issue in some devices.

### ISSUE THREAD

**Issue by mohsens22** [Microsoft/WindowsUIDevLabs#206] opened 2017-04-08 20:35 UTC
Dear,
I'm using the BackDropHost for my UI.
![image](https://cloud.githubusercontent.com/assets/22152065/24832220/f8a94814-1cbf-11e7-8481-397bf93da652.png)
I'm using the last commit of "SamplesNative" and "SamplesCommon" in the "Windows UI Dev Labs" repo.
Some times it used to run into an issue in my device and BackDropHost became black. I partially fixed it by making a transparent .PNG and using instead of Noise.jpg It becomes like this when it is in problem : 
![image](https://cloud.githubusercontent.com/assets/22152065/24832228/18466288-1cc0-11e7-9a66-47bb79a2530f.png)

But in some devices the hostbackdrop goes black (RS2).
![image](https://cloud.githubusercontent.com/assets/22152065/24832243/582d9f9c-1cc0-11e7-9840-ac90fc030240.png)

I'll be thankful if you find a way to fix.

**Comment by Odonno** [comment] 2017-04-22 11:15
@mohsens22 I have the same problem on my Surface (Creator's Update) but I suppose it only work for Windows 10 Insider builds.

**Comment by sohchatt** [comment] 2017-04-22 15:59
So that we can figure out what's going wrong, I request that you remove the png asset form the effect graph and observe the brush's behavior once again and let me know if it is as follows:

- When the app is in focus, you see blurred backdrop pixels from the desktop content beneath your app as in your first image.

- When the app is out of focus, the HostBackdropBrush turns transparent in color. This means you should see whatever XAML content is underneath it (unless you've set an explicit fallback color or chained HBB as part of your effect graph in a manner that blends or composites with other content). Are you observing the behavior only when the app is out of focus? If so, does the UIElement parent of the BackDropHost control have a black background color?

This behavior is by design and should be consistent on all desktop devices (Surface or not) and not just on Insider builds but also the Creator's Update.

Do let me know if this helps.

**Comment by Odonno** [comment] 2017-04-22 21:55
@sohchatt Oh. I deactivated the Battery Saver mode and it worked on my Surface. I can reproduce it many times so I think it can be the source of the problem.

**Comment by mohsens22** [comment] 2017-04-22 23:49
@sohchatt The black color was mostly because of noise.jpg but In my third picture I did not have a black content under BackDropHost and noise.png is a transparent picture.
@Odonno In my laptop backdrophost works just fine. But in other devices, I had some bad reports.

**Comment by tomzorz** [comment] 2017-04-24 08:59
@sohchatt we've just had a discussion about this on twitter https://twitter.com/tomzorz_/status/856412970267627520 

> When the app is out of focus, the HostBackdropBrush turns transparent in color. This means you should see whatever XAML content is underneath it (unless you've set an explicit fallback color or chained HBB as part of your effect graph in a manner that blends or composites with other content). Are you observing the behavior only when the app is out of focus? If so, does the UIElement parent of the BackDropHost control have a black background color?
> 
> This behavior is by design...

Why is this the case? Anyone who uses a multi-monitor setup will often leave windows inactive in front of other content... why break this? Or at least enable it on devices with AC power, there is zero reasons to block it because of perf./battery reasons there. (and even on portables: we could do this in Vista with much less powerful devices)

**Comment by martinsuchan** [comment] 2017-04-24 09:08
Same issue here, it looks like when the app is unfocused, the Backdrop Brush turns into solid color after two seconds. When focusing the app again it starts working again. Anyone can test and reproduce this behavior in my recently updated app [Skyrim Herbarium](https://www.microsoft.com/en-us/store/p/skyrim-herbarium/9wzdncrfjvfs).

Disabling the Backdrop Brush makes sense when the app is not visible, minimized, etc. but it looks like a bug in the app if the app is still visible, in multi monitor setup typically, and suddenly the backdrop effects stops working.

This definitely needs to be fixed in the framework, because right now this effect is pretty much useless. The easiest solution could be using screenshot of the Backdrop Brush effect when unfocused instead of solid color.

**Comment by tomzorz** [comment] 2017-04-24 09:33
@martinsuchan I completely agree, although I wouldn't use a screenshot. More than often I leave a window in front of changing content (think music video on youtube or a game) - I'd still think the app is broken if the content froze behind it.

**Comment by mohsens22** [comment] 2017-04-24 10:24
And there is a worse bug.
When I am using the hostbackdrop brush in compact splitview, the explorer.exe crashes. Mostly on dual screen, also reported in single screens.
But now I changed a little bit in the SamplesCommon project and made the HostBackDrop invisible while it runs into an issue; It made the bugs more tolerable.

**Comment by martinsuchan** [comment] 2017-04-30 11:39
Interesting discovery, Microsoft started using the Backdrop Brush in first party apps on Windows 10 Redstone 3 builds. The [Maps](https://enterinit.com/windows-maps-app-update-with-project-neon-ui-in-windows-10-for-pcs-and-mobile/) and Groove apps already uses this backdrop blur.  
It's even more interesting that this effect does not disappear when unfocusing the app.
I've tried running my app on this version of Windows and the Blur keeps disappearing, just like on W10 CU. I guess there must be some kind of new API or manifest settings to keep the Blur enabled even when the app is not focused.

**Comment by Odonno** [comment] 2017-04-30 11:55
@martinsuchan I checked and indeed Microsoft used the BackdropBrush on these apps. However here is what I know : 

* Maps only use BackdropBrush to create a FrostedGlass effect (on top of the background app and not on top of the background of the OS). Used for a lot of control but mainly for the TopAppBar.
* Groove use both BackdropBrush and HostBackdropBrush. 
    * The first one is for a FrostedGlass effect for the BottomAppBar
    * The second one is for a "Acrylic" ? effect used for the HamburgerMenu. It works great but when the app loses focus, the background goes white instantly. So I think they did like @mohsens22 by putting a background color/image to prevent the "black" background

**Comment by mohsens22** [comment] 2017-04-30 12:31
@Odonno So, HostBackDrop has a long way for working correctly. 
BTW, have you seen that hover animation called "Reveal experience" that is in my people?
Is it a good library for implementing that?

**Comment by Odonno** [comment] 2017-04-30 12:56
@mohsens22 Sorry, I will clarify the API : 

* BackdropBrush was introduced with Anniversary Update and it works perfectly to create what Microsoft call a Frosted Glass effect. It is an effect that apply a kind of blur/transparency on top of any app control (like Maps where you have the AppBar on top of the Map control)
* HostBackdropBrush was introduced with Creators Update and that's what we are talking about (I don't know if it should be called "Acrylic" effect). Anyway, the objective is to act like BackdropBrush but you can apply this effect on top of the OS background. Like you can see with the HamburgerMenu of Groove app. And this one seems buggy, or maybe it was the intention to disable the effect when the app is not focused.

About the "Reveal experience" effect, I don't know if there is anything for that. On UWP Community Toolkit, there is only a Light effect. If you want a built-in control/effect, I suggest you to raise an issue here https://github.com/Microsoft/UWPCommunityToolkit

**Comment by JohnnyWestlake** [comment] 2017-05-16 08:37
Going off the Build talks, it looks like this behaviour is intentional for power / resource saving and visual reasons. Personally I'd rather not have it happen especially if I'm running and i7 GTX 1080 desktop machine (a small market slice admittedly).

**Comment by Odonno** [comment] 2017-05-16 12:07
Ok, so based on the news of the Build 2017, I learned that the `HostBackdropBrush` is disabled if one of these rules apply : 

* the device is on battery save mode
* the app is NOT in the foreground (does not have the focus)

The @windowsui team have the right arguments about that and I don't think they will change this behavior unless they receive a strong feedback from users. So I think we can close this issue.

**Comment by JustinXinLiu** [comment] 2017-05-17 02:21
Looks like there's a transition animation that changes the normal look to the fallback color. But the animation duration is so short that you can hardly realize it's animated.

I believe making it longer will provide better guidance for users to understand something has happened after an action (e.g. the app is now on the background).

**Comment by msftdavid** [comment] 2017-05-31 17:07
Closing the issue per suggestion

**Closed by msftdavid** 2017-05-31 17:07 UTC
Labels: bug
