### ISSUE TITLE
NavigationView class not registered exception in 16215

### ISSUE THREAD

**Issue by AudioW** [Microsoft/WindowsUIDevLabs#221] opened 2017-06-09 20:15 UTC
I have a navigation view and add menu items with the following code:

'Requested Windows Runtime type 'Windows.UI.Xaml.Controls.NavigationMenuItemSeparator' is not registered.'

When upgrading to 16215 today, this exception popped up on every type of navigation view item I try to add to the menu

Any ideas?

**Comment by hippieZhou** [comment] 2017-06-11 12:23
yes,I also got this exception,What should I do ?

**Comment by JustinXinLiu** [comment] 2017-06-12 11:23
Having the same issue here...

**Comment by msftdavid** [comment] 2017-06-19 22:36
We are aware of the issue, and are actively investigating the cause of the problem. I will try to give a more informative update once we have a better understanding of the fix.

**Comment by daneuber** [comment] 2017-09-11 16:00
Hi @JustinXinLiu  as an update on this issue, we've made changes that should fix this in a future insider flight.

**Comment by likuba** [comment] 2017-10-10 22:46
This should now be fixed in the most recent release.  Please reactivate if you are still seeing issues!

**Closed by likuba** 2017-10-10 22:46 UTC
Labels: bug
