### ISSUE TITLE
SetImplicitShowAnimation/SetImplicitHideAnimation doesn't not work within a ListView's ItemTemplate

### ISSUE THREAD

**Issue by JustinXinLiu** [Microsoft/WindowsUIDevLabs#222] opened 2017-06-16 11:05 UTC
When I try to use `SetImplicitShowAnimation`/`SetImplicitHideAnimation` to animate the `Visibility` of an element within a `ListView`'s `ItemTemplate`, no animations can be seen. However, if I change the `ListView` control to a `ListBox` with the rest of code untouched, the animations run correctly.

Is this a bug?

**Comment by shandilvarun** [comment] 2017-08-07 20:49
Is it on first show of the element or operations after it? do the animations play when the items first show up (load)?

**Comment by JustinXinLiu** [comment] 2017-08-07 22:27
@shandilvarun no the animations don't play at all.

**Comment by shandilvarun** [comment] 2017-08-08 16:28
@JustinXinLiu is there are simple repro that you can share?

**Comment by JustinXinLiu** [comment] 2017-08-09 00:13
@shandilvarun please see a full repo [here](https://github.com/JustinXinLiu/ImplicitShowHideAnimationBug).

**Comment by shandilvarun** [comment] 2017-09-18 17:44
@JustinXinLiu. sadly we don't have full show/hide coverage on listview as of this release. we are working on making our show/hide animations better and that will help solve item templates visibility issue. I will update this thread once we have made some changes and enable the scenario. this also applies to GridView. You should be able to animate complete item though.

**Comment by SeriousGeorge** [comment] 2017-11-24 09:23
@JustinXinLiu I made something similar with a gridview. 
Important is, that you bind your data with x:Bind and use x.Phase in your DataTemplate.

Like this for example:
```
<DataTemplate x:Key="myTemplate"><Image Opacity="{x:Bind imageOpacity, FallbackValue=1.0}" Source="{x:Bind thumbnail, Converter={StaticResource converter}}"  Stretch="UniformToFill" Tag=""  x:Phase="1">
</DataTemplate>
```

Then in the Gridview you're listening for contentchangings (e.g. an Image is about to be set by the binding):
```
<GridView x:Name="ItemGridView"
                  ItemsSource="{x:Bind Items}"
                  ContainerContentChanging="GridView_ContainerContentChanging" 
...
```

And then ChangingEvent itself:
```
private void GridView_ContainerContentChanging(ListViewBase sender, 
ContainerContentChangingEventArgs args)
        {
            if (args.Phase != 0)
            {
                throw new System.Exception("We should be in phase 0, but we are not.");
            }

            // It's phase 0, so this item's title will already be bound and displayed.
            if (cancelAllLoadings)
            {
                args.Handled = false;
                return;
            }
            args.RegisterUpdateCallback(ShowImage);
            args.Handled = true;
        }
```

And finally in phase 1, I'm animating everything in (fading the image to 1.0f):

```
 private void ShowImage(ListViewBase sender, ContainerContentChangingEventArgs args)
        {
            if (args.Phase != 1)
            {
                throw new System.Exception("We should be in phase 1, but we are not.");
            }

            // It's phase 1, so show this item's subtitle.
            if (cancelAllLoadings)
            {
                args.Handled = false;
                return;
            }

            Grid templateRoot = args.ItemContainer.ContentTemplateRoot as Grid;
            templateRoot.Opacity = 1;
            Visual gridVisual = GetVisualFromImage(templateRoot);
            gridVisual.Opacity = 0;
            scalarAnimationLibrary.Fade(gridVisual, compositor, 0.75f, new TimeSpan(0, 0, 0, 0, 350), new TimeSpan(0, 0, 0, 0, 0));
        }
```

Note... I wrote some helpers for getting visuals and animating stuff... so you could replace the lines with "GetVisualFromImage" and "scalarAnimationLibrary" with your own animating stuff.

I got this all from an article. 
Source: [https://blog.infeeny.com/2015/11/10/uwpxaml-compiled-binding-incremental-rendering-with-xphase/](https://blog.infeeny.com/2015/11/10/uwpxaml-compiled-binding-incremental-rendering-with-xphase/)

**Comment by stmoy** [comment] 2018-07-09 20:35
Due to the ListView control managing the lifecycle of its elements, implicit show and hide animations are not functional. This is a known limitation of implicit show/hide, and for the time being, this behavior is by design. We're actively investigating this scenario, but have nothing to report right now so I'm closing this thread.

**Closed by stmoy** 2018-07-09 20:35 UTC
Labels: animations, question
