### ISSUE TITLE
Bug: Shadows can end up outside of the app window

### ISSUE THREAD

**Issue by LostLogic** [Microsoft/WindowsUIDevLabs#80] opened 2016-05-11 05:54 UTC
I was playing around with the new SDK, and managed to produce an interesting shadow effect.

I am not sure if this is intended behaveour (Because it's kind of neat), but it would seem that the effects are not constrained to the size of the window. Check out the screenshot for a better idea what I mean (Bottom of the image)

![shadowbug](https://cloud.githubusercontent.com/assets/7568950/15171271/8d2dc4ac-174d-11e6-9861-28de4e9947e3.PNG)

**Comment by tomzorz** [comment] 2016-05-11 08:33
Haha this is awesome :D I imagine that someone somewhere didn't apply clip-to-window-bounds to the code that produces shadows in the compositor.

**Comment by pgills** [comment] 2016-05-11 15:49
@LostLogic Thanks for the playing around with the new APIs! 

I assume your configuration is:
- Windows Insider Build: 14332
- Windows SDK: 14332

We'll follow up and see if this is the expected behavior.

**Comment by LostLogic** [comment] 2016-05-11 17:44
@pgills The issue is present in both Insider Build 14332 with SDK 14332 and Insider Build 14343 with SDK 14332.

Let me know if you need any of the code I've thrown together to produce this issue :)

**Comment by pgills** [comment] 2016-05-11 18:04
Thanks for the build configurations that's super helpful.

**Comment by krenner** [comment] 2016-05-12 02:28
@LostLogic  This does look cool in your screen shot but is a known issue/expected and will be addressed in a future build.  Thanks for all the information.

**Comment by LostLogic** [comment] 2016-05-12 06:04
@kenner Cool! Glad it is on your radar.

Cheers!

I've found another shadow related bug. It would seem that only some fonts work when using TextBox as mask.

Code:
`private Compositor _compositor;

        private void EnsureCompositor()
        {
            if (_compositor == null)
            {
                _compositor = ElementCompositionPreview.GetElementVisual(this).Compositor;
            }
        }

        private void TextBlock_SizeChanged(object sender, SizeChangedEventArgs e)
        {
            if (e.NewSize.Width > 0 && e.NewSize.Height > 0)
            {
                EnsureCompositor();

                var textblock = sender as TextBlock;
                Debug.WriteLine($"LifeCounterPlayer: TextBlock_SizeChanged: Creating shadow for {textblock.Name}");

                var item = textblock.GetFirstAncestorOfType<RelativePanel>();
                var shadowContainer = (FrameworkElement) item.FindName($"{textblock.Name}Shadow");

                if (shadowContainer == null)
                {
                    var shadowRectangle = new Rectangle
                    {
                        Name = $"{textblock.Name}Shadow"     
                    };
                    Canvas.SetZIndex(shadowRectangle, 1);

                    shadowRectangle = shadowRectangle.CopyPositionToElement(textblock);

                    Debug.WriteLine("LifeCounterPlayer: TextBlock_SizeChanged: No Shadow block found, creating...");
                    item.Children.Add(shadowRectangle);
                    shadowContainer = (FrameworkElement)item.FindName($"{textblock.Name}Shadow");
                }

                // var textVisual = ElementCompositionPreview.GetElementVisual(textblock);

                //
                // Create a shadow object, and set the mask to be the text mask
                //
                var shadow = _compositor.CreateDropShadow();
                shadow.BlurRadius = 9;
                shadow.Color = Colors.Black;
                
                shadow.Mask = textblock.GetAlphaMask();

                shadowContainer.Height = textblock.DesiredSize.Height;
                shadowContainer.Width = textblock.DesiredSize.Width;

                // Position sprite directly behind the text block
                var shadowVisual = _compositor.CreateSpriteVisual();
                shadowVisual.Shadow = shadow;
                shadowVisual.Size = new Vector2((float) textblock.DesiredSize.Width,
                    (float) textblock.DesiredSize.Height);
                //shadowVisual.Offset = new Vector3(-shadowVisual.Size.X/2, -shadowVisual.Size.Y/2, 0.0f);

                ElementCompositionPreview.SetElementChildVisual(shadowContainer, shadowVisual);

            }//*/
        }`

With Segoe UI font
![shadow_notworking](https://cloud.githubusercontent.com/assets/7568950/15205489/0946e9f4-1818-11e6-80d9-49c25561ee89.PNG)

With custom font
![shadow_working](https://cloud.githubusercontent.com/assets/7568950/15205490/094758f8-1818-11e6-8927-25bc8a03391e.PNG)

**Comment by krenner** [comment] 2016-06-22 16:55
@LostLogic  Sorry for the delay!  Are you still having issues with shadow and Segoe UI?  I can't reproduce this.

**Comment by LostLogic** [comment] 2016-06-23 05:13
No worries @krenner ! I know you are all busy with Redstone at the threshold of release! :) I've been "forced" to reinstall 1511 to fix some issues I had with Visual Studio and publishing apps, so I can't go back and try to re-verify.
I suspect, however, that this issue could have been limited to the configuration I was running at the time.

**Closed** 2016-08-02 16:31 UTC
Labels: bug, question
