### ISSUE TITLE
ConnectedAnimationService doesn't behave properly with partially-off-screen targets

### ISSUE THREAD

**Issue by JohnnyWestlake** [Microsoft/WindowsUIDevLabs#77] opened 2016-05-03 18:17 UTC
Using build/SDK 14332 X64.

Essentially, using connected animation service, animate a target object from one page to another, but on the second page the item is partially off screen. In my case, the top 200 pixels of a 400 pixel high image is off screen. 

The ConnectedAnimationService animates to the correct position, but rather than clipping the top 200 pixels off, during the animation it top aligns the element to the top of the screen area and so cuts off the bottom 200 pixels instead. It also animates into a 200 pixel high rectangle, rather than properly honouring the -200 pixel top margin that should cause it to still be a 400 pixel square shape, just partially off-screen.

(I can get a repro project up tomorrow if that doesn't make sense)

(Also slightly unrelated, but is dragging scrollbars with a mouse resulting in glitchy behaviour a known issue? Seems to happen in all the UWP apps I try on this build)

**Comment by JasterAtMicrosoft** [comment] 2016-05-03 18:25
Thanks for reporting this issue @JohnnyWestlake! I believe this may be related to an bug that should be fixed on future insider builds. Please do attach a repro project though so I can verify.

Thanks,
Jacob

**Comment by JohnnyWestlake** [comment] 2016-05-04 09:01
[CASTest.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/248438/CASTest.zip)

See attached - with three different ways to aligning the image off the screen, all three being glitchy on 14332

**Comment by likuba** [comment] 2016-05-05 00:04
Also on the topic of your unrelated note on glitchy scrollbar scrolling--this is a known bug that we have been investigating internally--thanks for reporting!

**Comment by JasterAtMicrosoft** [comment] 2016-05-10 00:44
Hi @JohnnyWestlake ,

Thanks again for trying out ConnectedAnimationService and for providing the repro project! I have confirmed that a fix for this issue is coming in future Insider Preview builds and the image should render fine on the destination page.

Out of curiosity is there a particular reason why you are hiding half of the image or was this just the result of experimenting?

**Comment by JohnnyWestlake** [comment] 2016-05-11 08:35
Thanks!

So, I'm actually trying to replicate (in my opinion) one of Microsoft's finest pieces of UI design, the  Zune HD UI, [who's animations](https://youtu.be/o-UoLW0XkfA?t=103) ConnectedAnimationService should lend itself very nicely to helping out with. 

I have actually achieved it a while ago without CAS but it's a massive pain to maintain properly (and the animation changes in Windows 10 that screwed up *all* animations starting properly* didn't help). With support for custom easings CAS should be perfect for it - or failing that someway to manually disconnect a UIElement's Visual from the VisualTree and keep it alive to manually play with, though I understand that's probably just madness.

(*this is my biggest pet peeve. Nearly all XAML storyboards and ThemeTransitions I was using in Windows 8 / 8.1 apps don't perform anywhere near as nicely in Windows 10 since it first came out. Windows 10 skips easing functions, skips the start of the animation, seems to skip massive amounts of frames entirely when he wants too... which is really obvious to see when placing the same app side-by-side running on Windows Phone 8 / Windows Mobile 10 and the 8.1 app blows it away. Perhaps I should create a separate bug about that if that's something the team can look into and isn't by some important threading-change design or something)

**Comment by JasterAtMicrosoft** [comment] 2016-05-11 17:32
Hmm yeah if you could provide an example of something that regressed that would definitely be helpful. Those issues aren't expected. We did make an architectural change to animations in Windows 10 RTM that could have caused some changes but it's certainly not "by design" that we would be dropping frames.

**Closed** 2016-05-18 20:27 UTC
Labels: bug

**Comment by JasterAtMicrosoft** [comment] 2016-05-18 20:28
General theme transition issues now tracked in #83

**Comment by JohnnyWestlake** [comment] 2016-06-07 12:20
Thanks, seems to work now. Would look much nicer if it didn't crop the visual during the animation however! Especially if the target visual is actually rendered partially offscreen and not cropped, it kind of breaks the illusion it it pre-crops it too it's final "visible" size at the start of the animation, even though  that size is only a percentage of the actual targetElement size3

**Comment by shandilvarun** [comment] 2016-06-07 16:44
@JohnnyWestlake  do you have a screen grab of the experience you are seeing? can you share it here?

**Comment by JasterAtMicrosoft** [comment] 2016-06-07 17:24
Thanks for the feedback and for verifying the fix @JohnnyWestlake! We have a change coming in future Insider builds that introduces a cross-fade animation so you actually will see the unclipped visual for part of the animation.

The correct behavior for clipped elements in this API is an interesting question. There was some concern that if we always animate the unclipped visual then there will be a jarring "pop" as the connected animation element leaves or re-enters a clip at the start/end of the animation in certain scenarios. On the other hand, animating the unclipped visual is probably better for cases like an element that is partially off-screen. For various reasons we ended up choosing a policy for this release where we will get the snapshot for the connected animation visual from whatever would normally appear on-screen, which may be clipped. In practice this seems to work well for most cases, especially with the upcoming cross-fade animation. But you're certainly welcome to disagree and we appreciate the feedback.

**Comment by JohnnyWestlake** [comment] 2016-06-10 10:28
Thanks for the replies!

I mean, I'd personally prefer it to just animate the actual resultant rendered XAML which isn't clipped, (even if the displayed visual on screen is 400x100, the actual RenderSize is still 400 x 400?). I imagine if people are doing designs with ScrollViewers and stuff and starting their CAS target partially offscreen it'll look strange too. I'd certainly vote for doing it a bit differently in the future! At the moment I'm probably going to have to stick with the more hassle-y storyboard solution I have.

Attached a little update to the above project that tries to exacerbate it - combined with the crossfade it ends up looking glitchy. The page backwards animation looks to work perfectly nicely though starting from offscreen!

[CASTest2.zip](https://github.com/Microsoft/WindowsUIDevLabs/files/308811/CASTest2.zip)
