### ISSUE TITLE
Method not found: 'Void Windows.UI.Composition.Visual.put_Size(System.Numerics.Vector2)'

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#112] opened 2016-06-29 23:12 UTC
I am currently on **Build 14376**, **SDK 14366** and **Visual Studio Update 3**.
I am creating a custom UWP control. In the **ArrangeOverride()** method of the control I am creating a few visuals and adding them to the visual tree.

Now when I add this control to the XAML, in the XAML Designer, it shows the following error

`Method not found: 'Void Windows.UI.Composition.Visual.put_Size(System.Numerics.Vector2)'`

Debugging the XAML Designer gives the following information

```
An exception of type 'System.MissingMethodException' occurred in Microsoft.VisualStudio.DesignTools.UniversalXamlDesigner.DLL and wasn't handled before a managed/native boundary

Additional information: Method not found: 'Void Windows.UI.Composition.Visual.put_Size(System.Numerics.Vector2)'.
```

It would be great if you could tell me how to resolve this issue.

**Comment by pgills** [comment] 2016-07-08 21:30
Following up with @msftdavid and @JasterAtMicrosoft to see if this is a known Designer issue or not.

**Comment by decademoon** [comment] 2016-09-21 08:09
Any update on this? I have the same problem too. It's really annoying because it completely breaks the designer and XAML editor (the entire XAML has blue squiggle underlines). I'm using Visual Studio Community version 14.0.25431.01 Update 3.

I thought avoiding any composition stuff if `DesignMode.DesignModeEnabled` is true would fix the problem, but it didn't.

Interestingly, if I use this code it fixes the designer:

```
// FIXME: This function wrapper is needed otherwise the XAML designer errors.
Action func = () =>
{
    tracker.MinPosition = new Vector3(0, float.NegativeInfinity, 0);
    tracker.MaxPosition = new Vector3(0, float.PositiveInfinity, 0);
};
func();
```

**Comment by msftdavid** [comment] 2016-09-27 22:45
@decademoon , for reference, what Windows build (Anniversary Update, Insider, etc...) are you currently encountering this issue on? And which SDK version are you using?

**Comment by decademoon** [comment] 2016-09-27 22:52
@msftdavid OS build 14393.187, SDK 14393

**Comment by yanjingenious** [comment] 2016-09-30 04:02
同14393.187系统，SDK14393，问题出在2个阴影示例的XAML设计器

**Comment by sirtwist** [comment] 2016-10-19 05:24
I'm getting this same error trying to use the UWP Community Toolkit ... trying to use their Blur animation on an image. The exception is happening in their Microsoft.Toolkit.Uwp.UI.Animations.DLL.

An exception of type 'System.MissingMethodException' occurred in Microsoft.Toolkit.Uwp.UI.Animations.DLL but was not handled in user code

Additional information: Method not found: 'Void Windows.UI.Composition.Visual.put_Size(System.Numerics.Vector2)'.

Running on Build 14946 using SDK 14393 using the latest UWP Community Toolkit (1.1 I believe)

**Comment by NatMarchand** [comment] 2016-10-21 14:14
Same for me :
Build 14931, SDK14393 

> Method not found: 'Void Windows.UI.Composition.Vector3KeyFrameAnimation.InsertKeyFrame(Single, System.Numerics.Vector3)'.: System.MissingMethodException: Method not found: 'Void Windows.UI.Composition.Vector3KeyFrameAnimation.InsertKeyFrame(Single, System.Numerics.Vector3)'.

**Comment by disklosr** [comment] 2016-10-22 15:02
I have the same issue.

I created this repo to so you can reproduce the problem: https://github.com/disklosr/Vector3Issue

**Comment by msftdavid** [comment] 2016-11-10 01:31
Thank you all for the information, and thanks @disklosr for the reduced project. We are having a difficult time reproducing it, although it doesn't seem as though it should be that hard from everyone's comments.

If possible, I'd like to confirm the steps involved:
1. Launch the project (say, Vector3Issue).
2. Open in XAML designer a page with a custom XAML control added to it.

I was not able to reproduce using Vector3Issue even after adding more ShadowControl elements to the page. Additionally, pages in the UWP Toolkit open properly in XAML designer as well, even on those pages that use Composition. Is there something special that I have to do that I'm missing here?

**Comment by disklosr** [comment] 2016-11-13 13:46
@msftdavid After investigation, turned out the problem only occurs in x86 / x64 configuration. By default the project opens with an ARM config, so just change it to x86 and the designer of MainPage should break.

**Comment by JustinXinLiu** [comment] 2016-12-06 03:49
I am also getting this annoying issue. @msftdavid wonder if you have been able to reproduce it yet?

**Comment by JustinXinLiu** [comment] 2016-12-06 04:41
For the time being I am able to work around the issue by putting this check inside my custom shadow control.
```
        public ShadowWrapper()
        {
            DefaultStyleKey = typeof(ShadowWrapper);

            if (Windows.ApplicationModel.DesignMode.DesignModeEnabled) return;
```

**Comment by JustinXinLiu** [comment] 2016-12-06 20:47
I asked Unni from the VS team and this is what he told me -

> Yes, we are aware of this limitation, and in the near term, this is “by design”. You will need to guard all code that tries to access such APIs with design mode checks, so they don’t execute in the designer and work fine in the running application.
>  
> Long term, we will be addressing this. Please stay tunes for updates on this front next year.

So yeah they are aware of this. :)

**Comment by Liero** [comment] 2016-12-13 14:27
How to debug the Visual Studio Designer? I've tried attach another instance of visual studio wih the same solution opened to all XDesProc processes, but no exception was caught. How do I find where is the code I need to safeguard from running in designer?

**Comment by disklosr** [comment] 2016-12-13 14:56
@Liero you shoud guard any code that uses a reference to System.Numerics.Vector (or any other problematic types that the designer error reports)

If you download the sample i shared earlier in this thread you'll find an example of a guard condition that makes the designer happy

**Comment by h82258652** [comment] 2017-03-10 02:24
still not fixed in VS2017.
![snipaste20170310_102402](https://cloud.githubusercontent.com/assets/5144550/23779491/b99e87b6-057b-11e7-9284-66a92b407ed4.png)

**Comment by zipgenius** [comment] 2017-03-16 10:10
I can confirm: it's not fized in VS2017 for ANY of Community controls.

**Comment by planetarian** [comment] 2017-04-07 21:54
I am encountering this as well.

**Comment by Liero** [comment] 2017-04-10 12:46
Vote here pls: https://visualstudio.uservoice.com/forums/121579-visual-studio-ide/suggestions/18892300-fix-the-uwp-designer-errors

Maybe somebody will finally pay attention

**Comment by michaelcoelsch** [comment] 2017-08-22 08:57
Still no fix for this problem. Are you not able to solve that problem after such long time???

**Comment by JustinXinLiu** [comment] 2017-08-22 09:30
@michaelcoelsch which version of VS are you using? This is fixed on mine.

**Comment by michaelcoelsch** [comment] 2017-08-22 10:12
Microsoft Visual Studio Enterprise 2017 
Version 15.3.1
VisualStudio.15.Release/15.3.1+26730.8
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Enterprise

**Comment by JustinXinLiu** [comment] 2017-08-22 11:23
@michaelcoelsch hmm, I am using the same. Which control is not rendering for you on the Designer?

**Comment by michaelcoelsch** [comment] 2017-08-22 11:43
it is the DropShadowPanel

**Comment by JustinXinLiu** [comment] 2017-08-22 11:58
Interesting. I have been able to render that in the last few VS updates.

<img width="1007" alt="shadow" src="https://user-images.githubusercontent.com/1710184/29564401-efaa4d8c-8784-11e7-819e-3828b4c65ee7.PNG">

**Comment by michaelcoelsch** [comment] 2017-08-22 12:17
I am using the DropShadowPanel control from UWP Community Toolkit Version 1.5.1 and still have these issues in the designer:

Method not found: 'Void Windows.UI.Composition.Visual.put_Size(System.Numerics.Vector2)'.

**Comment by daneuber** [comment] 2017-10-11 19:04
Hi @michaelcoelsch are you still encountering this issue? I've just tested DropShadowPanel from UWP Community Toolkit (both versions 2.0.0 and 1.5.1) with VS Enterprise 2017 v 15.3.4 and I am not seeing his issue. The associated issue on the community toolkit thread appears to be closed as fixed - https://github.com/Microsoft/UWPCommunityToolkit/issues/1358

**Comment by jefhai** [comment] 2017-11-14 19:28
@daneuber I am seeing this issue with Toolkit 1.5.1 in VS Community 15.4.4.

**Comment by daneuber** [comment] 2018-04-13 20:47
Hi all, sorry for the delay. After communicating with the UWP Toolkit folks this should be fixed in these PRs: 

- [https://github.com/Microsoft/UWPCommunityToolkit/pull/1413](https://github.com/Microsoft/UWPCommunityToolkit/pull/1413)

- [https://github.com/Microsoft/UWPCommunityToolkit/pull/1486](https://github.com/Microsoft/UWPCommunityToolkit/pull/1486)

You'll notice one of the issues mentioned in those PRs [(https://github.com/Microsoft/UWPCommunityToolkit/issues/1224)](https://github.com/Microsoft/UWPCommunityToolkit/issues/1224) has the same Vector2 error message that's been discussed on this thread. Seeing as how the fix has been verified I'm going to close this issue out. If upon updating this is still a problem, please open a new github issue using the template to share detailed repro steps and machine configuration details. Thank you for your patience through this long thread.

**Closed by daneuber** 2018-04-13 20:47 UTC
Labels: bug
