### ISSUE TITLE
Natural Motion > Z-Order Scrolling > Incorrect header text positioning

### ISSUE THREAD

**Issue by kmgallahan** [Microsoft/WindowsUIDevLabs#254] opened 2017-10-14 12:23 UTC
As per the title:

1. Visit the Natural Motion > Z-Order Scrolling sample
2. Scroll down
3. The "Chief Executive Officer" text is displayed too low so that it's hanging off the header background

This is on Windows 10 build 15063.674, app version 1.1.19.0

**Comment by daneuber** [comment] 2018-03-07 18:28
Hi @kmgallahan quick update we've confirmed this is fixed with the most recent push in this repo - Commit df23041678599e54e4d21e3a9a67526b28df6e4a, though the store app has not been updated yet. Let us know if this fixes the issue.

**Comment by daneuber** [comment] 2018-07-03 17:53
@kmgallahan closing since this appears to be fixed and no longer repros on our end now. Please re-open if you are able to verify this is still an issue on the updated store app or GitHub repo.

**Closed by daneuber** 2018-07-03 17:53 UTC
Labels: bug, gallery
