### ISSUE TITLE
Shadows in second monitor and other geometries

### ISSUE THREAD

**Issue by juanpaexpedite** [Microsoft/WindowsUIDevLabs#198] opened 2017-02-24 05:26 UTC
Might be I am the only one, but the Shadows do not work when I move the window from the first screen to the second one, if I have the window in both, only the first part has shadows.

Apart, what about having a corner radius in a border, will be have a generic way to get the alpha mask in order to do not be worry about how to get to apply to the get the shadow?

**Comment by daneuber** [comment] 2017-02-24 18:43
Hi @juanpaexpedite thanks for the feedback. We're actively looking at the shadows issue and will provide an update soon.

For clarification on your second point, are you saying you want the shadow by default to take the shape of the visual it's applied to?

**Comment by juanpaexpedite** [comment] 2017-02-25 08:21
Hello, taking the example ShadowPlayground from the SampleGallery if we add a border inside the common CompositionShadow
![image](https://cloud.githubusercontent.com/assets/5947026/23329545/c2285dd8-fb32-11e6-94da-5d2fba5ce1d2.png)

A possible solution keeping the performance, might be  DropShadow : CompositionShadow, IDropShadow could have an option of BorderRadius, to apply it instead of calculate complex geometries. Just thinking.

Thank you for the reply,

**Comment by daneuber** [comment] 2017-02-27 22:52
@juanpaexpedite Thanks, we've received similar feedback from other customers (see issue #162 ) and unfortunately don't have a straightforward solution for this yet. As far as other solutions, in the other linked issue mentioned you'll see you can either get the desired result with...
1. Custom rendering into a CompositionDrawingSurface, wrapping with a SurfaceBrush, then applying it as a .Mask property input,
 or by 
2. Using [CompositionProToolkit ](https://github.com/ratishphilip/CompositionProToolkit) @ratishphilip

Hopefully one of those solutions is useful for you! We'll take note of your feedback and continue to think about the issue further.
As an update, we're still looking at the other shadow issue you mentioned.

**Comment by juanpaexpedite** [comment] 2017-03-01 09:34
About the first option, I understand I can create a runtime component in C++ to render shadows for instance? I've just used composition runtime only for DirectWrite, I will try to find an example on how to do that, any advice on how to start? I also have made ton of work in Win2D...

Yes I have used the great toolkit from @ratishphilip, before, It's just to know the roadmap direction of Composition. 

Thank you

**Comment by daneuber** [comment] 2017-03-01 23:32
You can use either native C++ (Direct2D/Direct3D/DirectWrite/Win2D) or C# (Win2D) to fill out a CompositionDrawingSurface with the shape you’d want to use as a shadow. You can then use a SurfaceBrush pointing to this surface as your shadow’s mask property.

On another note we were able to root cause the problem you mentioned in your original comment about shadows disappearing in some cases in multiple monitor scenarios. A fix for this should be available on insider builds in the near future.

**Comment by msftdavid** [comment] 2017-03-08 23:39
Looks like this is resolved. Closing.

**Closed by msftdavid** 2017-03-08 23:39 UTC
