### ISSUE TITLE
GetScrollViewerManipulationPropertySet.Translation always zero

### ISSUE THREAD

**Issue by Mr1Penguin** [Microsoft/WindowsUIDevLabs#246] opened 2017-09-11 11:34 UTC
Hello!

I  tried to use GetScrollViewerManipulationPropertySet to make an animation but it didn't work.

I create this handler for ScrollViewer.ViewChanging to get translation values for every moment. And everytime I get a <0,0,0> value.

``` csharp
private void SV_ViewChanging(object sender, ScrollViewerViewChangingEventArgs e)
{
    ElementCompositionPreview.GetScrollViewerManipulationPropertySet(SV).TryGetVector3("Translation", out var t); // success
    Debug.WriteLine($"<{t.X},{t.Y},{t.Z}>");
}
```

I have a thought that I doing something wrong but I have no idea what exactly. 

min sdk: 14393
target sdk: 15063

OS
Desktop: 15063.540, 16281.1000
Mobile: 15245.0

**Comment by patsiu** [comment] 2017-09-11 15:44
Hey @Mr1Penguin!

Thanks for reaching out with your question. In general, what you're seeing is by design, so let me give you some details to help explain:

- GetScrollViewerManipulationPropertySet() does pass back a CompositionPropertySet with a Property called Translation but that value will not get updated on the app side, only the system side. This is why you are always seeing a <0,0,0> value.
- This PropertySet you get back is not a way to simply query how much a XAML ScrollViewer has moved, but instead a way to tie into a CompositionAnimation. 
- This PropertySet ultimately represents a "reference" that you can use in a Composition ExpressionAnimation, where you want to create an animation experience based on the translation of a XAML ScrollViewer. (Check out the [Parallaxing List Items ](https://github.com/Microsoft/WindowsUIDevLabs/blob/master/SampleGallery/Samples/SDK%2010586/ParallaxingListItems/ParallaxingListItems.xaml.cs)sample to see this in action)

Out of curiosity, what are you trying to do with the ScrollViewerManipulationPropertySet??

Thanks!

**Comment by Mr1Penguin** [comment] 2017-09-11 16:18
Thanks for answers!

First item helped me realize that a error somewhere in expression. And I found it! The problem was decreasing Translate value instead of increasing it while scrolling to bottom. So I just add '-' for every Translate.Y.

I tried to make a sticky row-header inside a scrollviewer. 

``` csharp
CompositionPropertySet scrollerManipProps = ElementCompositionPreview.GetScrollViewerManipulationPropertySet(SV);

_oa = cm.CreateExpressionAnimation();
// *v - rows inside Grid
_oa.SetReferenceParameter("gv", gv); 
_oa.SetReferenceParameter("rv", rv);
_oa.SetReferenceParameter("bv", bv);
_oa.SetReferenceParameter("yv", yv);
_oa.SetReferenceParameter("iv", iv);
_oa.SetReferenceParameter("kv", kv);
_oa.SetReferenceParameter("sp", scrollerManipProps);
_oa.Expression = "Matrix4x4(" +
                "1, 0, 0, 0," +
                "0, 1, 0, 0," +
                "0, 0, 1, 0," +
                "0, (-sp.Translation.Y <= gv.Size.Y ? 0 : (-sp.Translation.Y <= gv.Size.Y + bv.Size.Y ? -sp.Translation.Y - gv.Size.Y : (-sp.Translation.Y <= gv.Size.Y + rv.Size.Y + bv.Size.Y ? bv.Size.Y : 0))), 0, 1)";
rv.StartAnimation(nameof(Visual.TransformMatrix), _oa);
```

**Comment by daneuber** [comment] 2017-09-11 16:28
@Mr1Penguin it appears this issue is resolved so going to go ahead and close it out. Please re-open if you are still experiencing issues.

**Closed by daneuber** 2017-09-11 16:28 UTC
Labels: animations
