### ISSUE TITLE
composition image control throws memory exception on mobile

### ISSUE THREAD

**Issue by touseefbsb** [Microsoft/WindowsUIDevLabs#236] opened 2017-08-02 12:11 UTC
I tried to run sample gallery app on mobile emulator ( anniversary edition ) and even tried to install sample app from store and ran that, but the app opens the homepage for about 2 secs and then crashes. with composition image control giving some memory exception

**Comment by peterfelts** [comment] 2017-08-09 17:53
Thanks for reporting this. We were able to reproduce what you're seeing. We also noticed that if you disable visual UI debugging tools for XAML (project options > Debugging > General > "Enable UI Debugging Tools for XAML") the exception doesn't occur. We've created an internal bug to track this.

**Comment by touseefbsb** [comment] 2017-08-10 08:56
Oh ok thanks for telling me the work around

**Comment by daneuber** [comment] 2017-08-28 21:32
Closing since workaround has been provided and we're tracking this. Please let us know if you continue to experience issues.

**Closed by daneuber** 2017-08-28 21:32 UTC
Labels: bug
