### ISSUE TITLE
How to rotate perspectively ??

### ISSUE THREAD

**Issue by assassin316** [Microsoft/WindowsUIDevLabs#22] opened 2016-03-03 01:35 UTC
I have a Grid control that has content in it and I would simply like to rotate the Grid, say 30 degrees along the Y-axis, when it's Loaded. I did the following but it doesn't work, produces an error:

	var uiElement = sender as UIElement;

	// Initialize the Compositor
	_root = ElementCompositionPreview.GetElementVisual(uiElement);
	_compositor = _root.Compositor;

	ExpressionAnimation expression = _compositor.CreateExpressionAnimation("Matrix4x4.CreateRotationY(angle)");
	expression.SetScalarParameter("angle", 30.0f);
	_root.StartAnimation("TransformMatrix", expression);

How do I go about doing the perspective rotation?

**Comment by tomzorz** [comment] 2016-03-03 10:48
Well there are multiple issues here:

a) this "_compositor = new Compositor();" is pointless

b) if you want to just rotate something instantly just set the parameter value dircetly (_root.TransformMatrix = Matrix4x4.CreateRotationY(30.0f);) or if you want to animate that over time use a keyframe animation.

**Comment by assassin316** [comment] 2016-03-03 14:06
> this "_compositor = new Compositor();" is pointless

I create and store my compositor in a private variable in my class, so I don’t  see how this is pointless. It’s the primary object to work with.

> if you want to just rotate something instantly just set the parameter value dircetly (_root.TransformMatrix = Matrix4x4.CreateRotationY(30.0f);) or if you want to animate that over time use a keyframe animation.

This doesn’t fix my issue, in fact, it makes things less dynamic by hard coding the value. :/

**Comment by tomzorz** [comment] 2016-03-03 14:40
It is pointless, because 2 lines later you get the actual compositor from the app ("_compositor = _root.Compositor;") - the one you should use. 

Also, I don't see how you're not "hardcoding" the value with the expression animation way. Not to mention that what you do with that line doesn't do any animating actually...

**Comment by assassin316** [comment] 2016-03-03 15:27
Ohhh you're right!   sorry, that was a copy/paste error on my side  :)   yes the compositor was wrong, I just didn't notice my mistake. Now I understand.

My goal is simply to rotate the uiElement (in this case, a Grid) 30 degrees on the y-axis, to give it a perspective look, like this:

[http://vbcity.com/cfs-filesystemfile.ashx/__key/CommunityServer.Blogs.Components.WeblogFiles/xtab.metablogapi/0407.PlaneProjection_5F00_28D921D6.png](url)

I'm guessing this is not so simple ??  I'm still very new to Composition.   :\

I get this error when I run it:

**The parameter is incorrect. One or more parameters have not been set on the ExpressionAnimation.**

**Comment by robmikh** [comment] 2016-03-03 19:48
Hey assassin316,

CreateRotationY is actually not a supported function in the expression engine. To see a list of supported functions check out this link: https://msdn.microsoft.com/en-us/library/windows.ui.composition.expressionanimation.aspx

However, if you write the expression or create a matrix and call CreateRotationY and assign it to TransformMatrix manually you won't get the perspective you want. What you'll see is an orthographic projection.

To do perspective you'll need to go to the parent visual and apply a projection matrix. After that children what have 3D transforms should have projection. I can post some code when I'm back at my desk, I'm currently on my phone.

**Comment by assassin316** [comment] 2016-03-03 20:28
Thanks robmikh,
If you can show me that would be a great help. I had found this link which also does the rotation, but it seems it might be old code, couldn't get it to work:

[https://msdn.microsoft.com/en-us/magazine/mt590968.aspx](https://msdn.microsoft.com/en-us/magazine/mt590968.aspx)

**Comment by robmikh** [comment] 2016-03-03 22:31
This will get you the following:
http://i.imgur.com/pXZhX4L.png

So for reference my XAML looks like this:
```
<Grid x:Name="ParentGrid">
    <Rectangle x:Name="ChildRectangle" HorizontalAlignment="Center" VerticalAlignment="Center" Width="100" Height="100" Fill="Blue" />
</Grid>
```

The first step is to create the perspective projection matrix:
```
var parent = ElementCompositionPreview.GetElementVisual(ParentGrid);

float depth = 500.0f;
var projectionMatrix = new Matrix4x4(1, 0, 0, 0,
                                     0, 1, 0, 0,
                                     0, 0, 1, -1 * (1 / depth),
                                     0, 0, 0, 1);

var cameraMatrix = Matrix4x4.CreateTranslation(0, -100.0f, 0) *
                   projectionMatrix *
                   Matrix4x4.CreateTranslation(0, 100.0f, 0);

parent.TransformMatrix = cameraMatrix;
```

The second step is to put the rotation on the child:
```
var child = ElementCompositionPreview.GetElementVisual(ChildRectangle);

child.TransformMatrix = Matrix4x4.CreateRotationY(30.0f);
```

Granted, this is just one way of doing so. The method you posted in that article should still work. Do you mind posting a snippet of what you have setup?

**Comment by assassin316** [comment] 2016-03-08 16:52
Hi robmikh, sorry for the delay to your post...

So I'm testing with a simple setup consisting of a Grid with a ListView in it, and below is the code I have to perform the rotation animation on the Grid. Currently it performs the rotation with no errors, thanks to you :)  But the animation doesn't occur, I coded this using a mix of your code and that from the "Windows Composition Turns 10" article link I mentioned previously...

	MainGrid.Loaded += (sender, e) =>
	{
		var uiElement = sender as UIElement;

		var width = (float)(sender as FrameworkElement).ActualWidth;
		var height = (float)(sender as FrameworkElement).ActualHeight;

		TimeSpan duration = TimeSpan.FromMilliseconds(1000);

		// Initialize the Compositor
		_root = ElementCompositionPreview.GetElementVisual(uiElement);
		_compositor = _root.Compositor;

		var easing = _compositor.CreateLinearEasingFunction();
		
		// Scalar keyframe animation for the rotation angle
		ScalarKeyFrameAnimation rotate = _compositor.CreateScalarKeyFrameAnimation();
		rotate.InsertKeyFrame(0.0f, 30.0f);
		rotate.InsertKeyFrame(1.0f, 0.0f, easing);
		rotate.Duration = duration;

		// Define a custom object with a property to refer from within an expression
		CompositionPropertySet rotation = _compositor.CreatePropertySet();
		rotation.InsertScalar("Angle", 0.0f);
		rotation.StartAnimation("Angle", rotate);

		// To ensure that the rotation occurs through the center of the visual rather than the
		// left edge, pre-multiply the rotation matrix created by CreateFromAxisAngle
		// with a translation that logically shifts the axis to the point of rotation
		var pre = Matrix4x4.CreateTranslation(-width / 2.0f, -height / 2.0f, 0.0f);

		// Add some perspective and then restore the visual to its original location
		float depth = 5000.0f;
		var rotateMatrix = new Matrix4x4(1, 0, 0, 0,
										 0, 1, 0, 0,
										 0, 0, 1, -1 * (1 / depth),
										 0, 0, 0, 1);
		var restoreMatrix = Matrix4x4.CreateTranslation(width / 2.0f, height / 2.0f, 0.0f);
		var post = rotateMatrix * restoreMatrix;

		// Define a transform matrix to produce the desired effect, while delegating
		// to the animated "Angle" property for the rotation angle itself
		ExpressionAnimation expression = _compositor.CreateExpressionAnimation("Pre * Matrix4x4.CreateFromAxisAngle(axis, rotation.Angle) * Post");

		expression.SetVector3Parameter("axis", new Vector3(0.0f, 1.0f, 0.0f));
		expression.SetReferenceParameter("rotation", rotation);
		expression.SetMatrix4x4Parameter("Pre", pre);
		expression.SetMatrix4x4Parameter("Post", post);

		_root.StartAnimation("TransformMatrix", expression);
	}

Simply xaml for this:

    <Grid Margin="8"
		  x:Name="MainGrid"
		  DataContext="{Binding Source={StaticResource SampleDataSource}}">
		<ListView ItemsSource="{Binding Groups}"
				  ItemTemplate="{StaticResource ListItemTemplate}"
				  ItemContainerStyle="{StaticResource ContainerStyle}"/>
	</Grid>

**Comment by robmikh** [comment] 2016-03-09 03:11
Hmmm... so your code actually works for me. One thing to note, CreateFromAxisAngle actually takes radians, and not degrees. The way it is now the ListView spun around multiple times for me. Converting the angle to radians gave it a much smoother transition, which I assume is what you were trying to achieve.

Do you mind attaching a reduced sample solution that reproduces this issue for you? There might be something outside the code snippets that we're doing differently. Additionally, what build of Windows 10 are you on? You can find this by going to the Settings app and navigating to System->About. It should be listed as "OS Build".

**Comment by assassin316** [comment] 2016-03-09 14:23
Whoa, you're absolutely right, I created a new project and placed the code exactly as I did, and it worked   :o

When I first placed the code in my post, I removed extra code for brevity, there must be another problem I have. I'll investigate and report back with the problem source!

Thanks Rob!!

**Comment by assassin316** [comment] 2016-03-09 14:48
Ok, I noticed a very strange problem, if you change the XAML to include two ListViews, it acts a little strange. In my case, when I keep a blank Grid, it works perfectly, but when I include two ListViews with scrollbars, it doesn't complete the rotation. Try the same code I pasted above, but change your XAML to the following:

	<Grid Margin="12"
		  Padding="12"
		  x:Name="MainGrid"
		  Background="Green">

		<Grid.ColumnDefinitions>
			<ColumnDefinition Width="*" />
			<ColumnDefinition Width="*" />
		</Grid.ColumnDefinitions>

		<ListView Background="Red">
			<x:String>Lorem ipsum dolor sit amet, consectetur adipiscing.</x:String>
			<x:String>Nunc fringilla ultrices est eu ornare.</x:String>
			<x:String>Suspendisse purus massa, iaculis in finibus dictum, gravida vel purus.</x:String>
			<x:String>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</x:String>
			<x:String>Donec vitae dolor imperdiet, vehicula enim quis, mollis tellus.</x:String>
			<x:String>Donec placerat diam sed est porttitor, venenatis semper mauris tempus.</x:String>
			<x:String>Sed placerat ipsum enim, quis porta nibh accumsan sit amet.</x:String>
			<x:String>Etiam tempus dapibus dolor, eget sollicitudin risus cursus eget.</x:String>
			<x:String>Vestibulum non rhoncus velit.</x:String>
			<x:String>Vestibulum volutpat, lacus quis laoreet accumsan, erat diam dignissim ligula.</x:String>
			<x:String>Vestibulum posuere consequat libero, at fermentum tellus tempus eget.</x:String>
			<x:String>Curabitur viverra nisl a augue porta luctus.</x:String>
			<x:String>Duis sodales metus et purus finibus, at tincidunt felis porta.</x:String>
			<x:String>Fusce elementum ut diam ut sodales.</x:String>
			<x:String>Nunc eget varius lectus.</x:String>
			<x:String>Fusce nec rhoncus arcu.</x:String>
			<x:String>Nunc feugiat, nulla non luctus dapibus, justo odio tincidunt libero, mattis commodo sem nulla sed tellus.</x:String>
			<x:String>Aliquam ut condimentum est, id euismod turpis.</x:String>
			<x:String>Donec nec orci nulla.</x:String>
			<x:String>Suspendisse faucibus mollis sapien, ac congue nulla aliquet vel.</x:String>
			<x:String>In hac habitasse platea dictumst.</x:String>
			<x:String>Duis dapibus sem a ullamcorper vestibulum.</x:String>
			<x:String>Aliquam varius imperdiet tortor vitae elementum</x:String>
			<x:String>Curabitur eget diam a neque blandit egestas.</x:String>
			<x:String>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</x:String>
			<x:String>Phasellus pulvinar laoreet ipsum ut scelerisque.</x:String>
			<x:String>Praesent eget molestie sem.</x:String>
			<x:String>Sed pretium suscipit orci, mollis interdum purus vestibulum vitae.</x:String>
		</ListView>
		
		<ListView Background="Blue"
				  Grid.Column="1">
			<x:String>Lorem ipsum dolor sit amet, consectetur adipiscing.</x:String>
			<x:String>Nunc fringilla ultrices est eu ornare.</x:String>
			<x:String>Suspendisse purus massa, iaculis in finibus dictum, gravida vel purus.</x:String>
			<x:String>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.</x:String>
			<x:String>Donec vitae dolor imperdiet, vehicula enim quis, mollis tellus.</x:String>
			<x:String>Donec placerat diam sed est porttitor, venenatis semper mauris tempus.</x:String>
			<x:String>Sed placerat ipsum enim, quis porta nibh accumsan sit amet.</x:String>
			<x:String>Etiam tempus dapibus dolor, eget sollicitudin risus cursus eget.</x:String>
			<x:String>Vestibulum non rhoncus velit.</x:String>
			<x:String>Vestibulum volutpat, lacus quis laoreet accumsan, erat diam dignissim ligula.</x:String>
			<x:String>Vestibulum posuere consequat libero, at fermentum tellus tempus eget.</x:String>
			<x:String>Curabitur viverra nisl a augue porta luctus.</x:String>
			<x:String>Duis sodales metus et purus finibus, at tincidunt felis porta.</x:String>
			<x:String>Fusce elementum ut diam ut sodales.</x:String>
			<x:String>Nunc eget varius lectus.</x:String>
			<x:String>Fusce nec rhoncus arcu.</x:String>
			<x:String>Nunc feugiat, nulla non luctus dapibus, justo odio tincidunt libero, mattis commodo sem nulla sed tellus.</x:String>
			<x:String>Aliquam ut condimentum est, id euismod turpis.</x:String>
			<x:String>Donec nec orci nulla.</x:String>
			<x:String>Suspendisse faucibus mollis sapien, ac congue nulla aliquet vel.</x:String>
			<x:String>In hac habitasse platea dictumst.</x:String>
			<x:String>Duis dapibus sem a ullamcorper vestibulum.</x:String>
			<x:String>Aliquam varius imperdiet tortor vitae elementum</x:String>
			<x:String>Curabitur eget diam a neque blandit egestas.</x:String>
			<x:String>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</x:String>
			<x:String>Phasellus pulvinar laoreet ipsum ut scelerisque.</x:String>
			<x:String>Praesent eget molestie sem.</x:String>
			<x:String>Sed pretium suscipit orci, mollis interdum purus vestibulum vitae. </x:String>
		</ListView>
	</Grid>

Let me know if you are able to repro the rotation problem, it should not fully rotate when the ListViews exist. For testing purposes, I put the rotation angle at **1.0f radians**.

**Comment by robmikh** [comment] 2016-03-10 06:12
I tried out your new XAML and kept the same code but changed the angle to start at 1 radian. The animation still plays just fine for me. Are you sure that MainGrid is firing the Loaded event? What happens when you instead setup and start the animation as a result of a button click event?

**Comment by assassin316** [comment] 2016-03-11 18:09
I don't know what's happening, when I apply the same code in a separate project, everything runs fine. But when I run it in my primary project, the same problem occurs. The difference is that I have the animations triggering in a Behavior on the Loaded event (which fires). And on my UI, I have more controls included. Other than that, it's the same thing. I'll keep investigating and see what causes the problem. Sorry I can't provide further details as I do not know why the rotation doesn't occur. The weird thing is, I have the rotate as part of a "batch" along with a zoom and fade, and the zoom and fade work, but not the rotate, that's what makes this odd.    :\

**Comment by assassin316** [comment] 2016-03-11 18:31
Found the problem!!   I have a sample you can download **[HERE](https://temp-share.com/f/jolcxzbvyj/c8154e9555f4248dc9708f1bbd6b872f1cdcf75100f1cb631153697fcdfa3eb7)**:

When you run the sample, it'll work. Then uncomment the XAML in the ItemTemplate, and you'll see the issue.

**Comment by assassin316** [comment] 2016-03-15 01:51
Have you tried the sample?   did you reproduce it ?

**Comment by robmikh** [comment] 2016-03-15 06:25
Thanks assassin316! I'm finally able to repro it. I'll investigate and get back to you.

**Comment by assassin316** [comment] 2016-03-15 16:07
Thanks Rob!  :)

**Comment by assassin316** [comment] 2016-03-21 16:09
Hi Rob, I fixed my problem by changing my rotation code to use the code you specified in #32. Everything works perfectly!  Thanks again!

**Closed** 2016-03-29 13:20 UTC
Labels: question

**Comment by dbots** [comment] 2016-04-18 01:00
Hi assassin316,

The issue with the rotation animation not completing is because you're applying the animation to an object (in your case, a PropertySet) that is falling out of scope and therefore being GC'd.

If you change that PropertySet to a member field, the animation completes as expected.

Animations do not keep CompositionObjects alive.  Instead, when the CompositionObject is ready to be destroyed, all animations that are running on it are stopped.

Also, if an expression is referencing a CompositionObject's property, and that object goes away, the expression will use the last calculated value for that referenced property.  This is why your expression seems "frozen" midway through, and not just blank or reset or something like that.

Hope this helps!

Anthony
