### ISSUE TITLE
Expressionanimations broken and different behaviour in RoationAngleInDegrees since 14393

### ISSUE THREAD

**Issue by SeriousGeorge** [Microsoft/WindowsUIDevLabs#164] opened 2016-09-16 13:41 UTC
Hi there,

I've seen this thread: https://github.com/Microsoft/WindowsUIDevLabs/issues/149
But my solution is set to 10586, not 14393. 

Still each machine running anniversary update has the expressenanimations broken (Offset.X and my assets are positioned with margins).

I tried to give the xaml elements alignment attributes and also tried to place them in broders... but stillnot working.

Also I noticed a difference in RotationAngle / RotationAngleInDegrees.
I made a little "wheel of luck" app. And in order to be able to spin again from the current position everything worked fine on 1586 with myVisual.RotationAngle. With machines on 14393 I have to use myVisual.RotationAngleInDegrees, otherwise the degrees would be totally off.

Best regards

Edit:
Some code... I had a bunch of cloud graphics, which I just animated off the screen and with a condition reset them.

**XAML:**
`Grid x:Name="Clouds" VerticalAlignment="Top" HorizontalAlignment="Left">
                    <Image Source="Assets/GameUI/wolke1.png" Width="492" Height="397" Margin="-197,538,437,-455" />
                    <Image Source="Assets/GameUI/wolke2.png" Width="493" Height="367" Margin="613,41,-374,72" />
                    <Image Source="Assets/GameUI/wolke1.png" Width="418" Height="279" Margin="1466,-12,-1152,213" />
                    <Image Source="Assets/GameUI/wolke1.png" Width="492" Height="397" Margin="1200,-6,-960,89" />
                    <Image Source="Assets/GameUI/wolke3.png" Width="418" Height="279" Margin="8,33,306,168" />
                    <Image Source="Assets/GameUI/wolke3.png" Width="418" Height="279" Margin="8,706,306,-505" />
                    <Image Source="Assets/GameUI/wolke3.png" Width="418" Height="279" Margin="1368,445,-1054,-244" />
                    <Image Source="Assets/GameUI/wolke4.png" Width="680"  Margin="1781,220,-1729,-186" />
                    <Image Source="Assets/GameUI/wolke3.png" Width="470"  Margin="2175,666,-1913,-548" />
                    <Image Source="Assets/GameUI/wolke3.png" Width="418" Height="279" Margin="1939,-64,-1625,265" />
                    <Image Source="Assets/GameUI/wolke3.png" Width="470"  Margin="2572,126,-2310,-8" />
                    <Image Source="Assets/GameUI/wolke4.png" Width="680"  Margin="-846,-179,898,213" />
                    <Image Source="Assets/GameUI/wolke1.png" Width="492" Height="397" Margin="-1280,272,1520,-189" />
                    <Image Source="Assets/GameUI/wolke2.png" Width="493" Height="367" Margin="2650,445,-2411,-332" />
                </Grid>`

**C#** (the x value 2736 is just a fixed value for a testcase)
` foreach (Image cloud in UIHelper.FindAllElementsInVisualTree<Image>(Clouds))
            {
                Visual cloudVisual = GetVisualFromImage(cloud);
                cloudVisuals.Add(cloudVisual);
                Debug.WriteLine(cloudVisual.Offset.X);

```
            Random rnd = new Random();
            float speed = rnd.Next(2, 8) / 10.0f;

            ExpressionAnimation parallaxAnimation = compositor.CreateExpressionAnimation("target.Offset.X > 2736 + target.Size.X- marginLeft ? 0 - marginLeft - target.Size.X*2 : target.Offset.X + Step");
            parallaxAnimation.SetScalarParameter("Step", speed);
            parallaxAnimation.SetScalarParameter("marginLeft", (float)cloud.Margin.Left);
            parallaxAnimation.SetReferenceParameter("target", cloudVisual);
            cloudVisual.StartAnimation("Offset.X", parallaxAnimation);
        }`
```

**Comment by patsiu** [comment] 2016-09-19 16:42
Hey @SeriousGeorge! 

Thanks for reaching out with your question. To make sure I fully understand what you're doing, two questions:
- For your ExpressionAnimations that are animating Offset.X, are you animating this property off a Visual you grabbed from a XAML element (ElementCompositionPreview) or a Visual you created off the Compositor?
- For your RotationAngle/RotationAngleInDegrees issue, can I assume you are using radians to define your angle when using RotationAngle and degrees with RotationAngleInDegrees? If so, can you provide some more details on what you're doing? (Maybe paste in a code snippet where you animate the property)

Thanks!

**Comment by SeriousGeorge** [comment] 2016-09-20 07:08
Hi @patsiu ,

**ExpressionAnimation**
Ah yes... sorry, I made a little helper-function which took care about some things. In there I grab the XAML Elements with "ElementCompositionPreview". 

Also I tried with parenting a Border and/or providing Alignmentvalues (as well as on the border, as on the images). No luck.

**RotationAngle**
Here's how I rotate it...

` ScalarKeyFrameAnimation animation = compositor.CreateScalarKeyFrameAnimation();
            animation.DelayTime = delay;
            animation.Duration = duration;
            animation.SetScalarParameter("start", from);
            animation.InsertExpressionKeyFrame(0.00f, "start");
            animation.SetScalarParameter("delta", to);
            animation.InsertExpressionKeyFrame(1, relative ? "start + delta" : "delta", easingFunction);
            visual.StartAnimation(nameof(visual.RotationAngleInDegrees), animation);`

The values are coming from a parameterized function.
But you can see that I need to spin relative. I take a "from" value, which is the current angle from the object and the "to" value.

I'm spinning  in fixed angles. The visual is seperated in 18° segments and I needed the visual to stop exactly in a multiple of 18°.

_1586 Build_
In 1586 I had to take visual.RotationAngle%360 to get the normalized (inside a 0-360° range) value to get the correct "from" value. If I had taken visual.RotationAngleInDegrees%360 I got awkward values, resulting in not spinning correctly (with an offset). I also had to store that in a seperate value, because if I directly referenced visual.RotationAngle in the "from" part the visual was spinning like mad and feelt like 3-4 fps.

_14393 Build_ (also valid for a 1586 Build running on a 14393 Windows)
In 14393 however, everything changed. I had to take visual.RotationAngleInDegrees%360 as the "from" value and everything spinned correctly whereas visual.RotationAngle%360 suddenly produced the offset.

Well I tricked myself around this as I difference between a Treshhold2 Windows and a Anniversary Windows and provide each mehtod as needed.

**Comment by patsiu** [comment] 2016-09-22 15:27
Hey @SeriousGeorge, 

Thanks for providing the additional info!

For the first issue with Expressions, you are definitely running into the conflict with XAML layout when animating Offset of a Visual retrieved via Element Composition Preview. This [MSDN link ](https://msdn.microsoft.com/en-us/windows/uwp/graphics/using-the-visual-layer-with-xaml)here gives some more information about this. I know you tried using a Border but try use the Border & Canvas combo that is described in the article. Let us know what happens, @JasterAtMicrosoft should also be able to help give some advice here as well.

For your rotation issue, want to clarify a few things here:
- When working with RotationAngle, are you under the assumption it is defined in Radians or Degrees? (Based on your description, you mod the RotationAngle property by 360, which definitely shouldn't be providing correct values as the property is defined in Radians)
- Is there a reason in your first Keyframe, you are not using "this.StartingValue" and creating a hard coded value?
- Can you also provide some code snippets on how you define your from and to values and how the relative condition is defined?

**Comment by SeriousGeorge** [comment] 2016-09-26 07:04
Hi @patsiu,

ok..I tried this:
` <Border>
                        <Canvas Margin="613,41,-374,72">
                            <Image Source="Assets/GameUI/wolke2.png" Width="493" Height="367"  />
                        </Canvas>
                    </Border>`

**and out of curiousity I tried also this:**
` <Border  Margin="-197,538,437,-455">
                        <Canvas >
                            <Image Source="Assets/GameUI/wolke1.png" Width="492" Height="397" />
                        </Canvas>
                    </Border>`

none of it worked.

And as a next step I reduced the animation logic to something simple:
`foreach (Image cloud in UIHelper.FindAllElementsInVisualTree<Image>(Clouds))
            {
                Visual cloudVisual = GetVisualFromImage(cloud);
                cloudVisuals.Add(cloudVisual);
                Debug.WriteLine(cloudVisual);

                Random rnd = new Random();
                float speed = rnd.Next(2, 8) / 10.0f;

                ExpressionAnimation parallaxAnimation = compositor.CreateExpressionAnimation("target.Offset.X + Step");
                parallaxAnimation.SetScalarParameter("Step", speed);
                parallaxAnimation.SetReferenceParameter("target", cloudVisual);
                cloudVisual.StartAnimation("Offset.X", parallaxAnimation);
            }`

still dosen't work.

**RotationAngle:**
Yes, I was aware that off course only RotationAngleInDegrees provides correct angle values. But results weren't correct. With RotationAngle they were (under 1586). In 14393 RotationAngleInDegrees worked as expected.

As for the "this.StartingValue". Oh.. I wasn't aware of that. Just tried it out. Works great. Thanks a lot.

**Comment by SeriousGeorge** [comment] 2016-09-26 07:15
One more thing I just noticed... yes it works, but the animation is just executed for 1 step. It's no longer animating continously. I just figured that out as I passed large offset values as a step and not small ones like 0.2. Should not target.Offset.X + 0.2f for example cause an expressionanimation to animate continously?

**Comment by patsiu** [comment] 2016-09-28 15:50
Thanks for the info @SeriousGeorge.

For the Offset issue, can you try target your app to the 10586 build and see if the issues still occur? (Looking at your markup code, we have a hunch, but want to verify).

For the RotationAngle problem, we can't repro the behavior you are seeing. Can you attach the full code snippet of how you calculate the "from", "to" and "delta" values?

**Comment by SeriousGeorge** [comment] 2016-09-30 07:44
I just deployed the app to a 10586 machine. The offset animation with the images wrapped in border and canvas is also working and animating (continously) there.

RotationAngle: The problem here is sorted. Providing this.StartingValue to the Animation just did the trick and works as expected on each build (10586/14393). I must had some hickup here since I waited after the animation completes with a task.delay (yeah, no good way) and then took the final (or as I thought) value of the rotated element.

**Comment by patsiu** [comment] 2016-09-30 15:09
Thanks for confirming @SeriousGeorge! Seems like you are running into the XAML / Composition Offset conflict. I'm going to have @JasterAtMicrosoft take a look at your markup to see what's missing.

**Comment by JasterAtMicrosoft** [comment] 2016-09-30 16:53
Hi @SeriousGeorge,

Can you clarify which element you are animating with the parallax animation? In the markup above you would need to target the Image element itself with the animation. Also, one of the Border/Canvas elements should be unnecessary.

**Comment by karmaecrivain94** [comment] 2016-10-02 20:52
I've got a similar issue here. I've got the following:
Pivot>PivotItem>Grid>GridView>GridView.Header>StackPanel>Grid

And I'm completely unable to animate the offset of that last grid with an expression animation. In fact, I can't seem able to animate the offset of anything inside that last StackPanel. Even if I replace it with a grid or another container.

**Comment by SeriousGeorge** [comment] 2016-10-04 11:50
Hi @JasterAtMicrosoft ,

it's right in my first post but the markup seems to be mixed up with for loops in here.
I've a Grid named "Clouds". In there are all my Images (now wrapped in borders and canvas).

Then I just grab the images like this:
` foreach (Image cloud in UIHelper.FindAllElementsInVisualTree(Clouds))
{
Visual cloudVisual = GetVisualFromImage(cloud);
cloudVisuals.Add(cloudVisual);

...

}`

So yes, I'm targeting the images directly.

**Comment by JasterAtMicrosoft** [comment] 2016-10-19 18:23
Sorry for the delay SeriousGeorge. On reviewing this more I think your expression animation may be malformed. It looks like the expression is "target.Offset.X + Step", where target is the Visual itself and Step is a constant.

I see what you are trying to do here, but the Expression engine doesn't really support animations that increment by a constant amount every tick. Instead I would recommend creating a ScalarKeyFrameAnimation with a linear easing function to animate the cloud until it leaves the screen. You can adjust the Duration of the animation to create different speeds.

The difference between versions you are seeing may be due to some optimizations done to expression animations to avoid evaluating the expression too often. As a result, the expression will just evaluate once instead of continuously.

**Comment by hanselo** [comment] 2016-11-03 18:58
Closing as it seems the cause has been found.

**Closed by hanselo** 2016-11-03 18:58 UTC
Labels: bug
