### ISSUE TITLE
TypeLoadException: Requested Windows Runtime type 'Microsoft.Graphics.Canvas.Effects.ArithmeticCompositeEffect' is not registered.

### ISSUE THREAD

**Issue by ratishphilip** [Microsoft/WindowsUIDevLabs#79] opened 2016-05-06 20:21 UTC
Build + SDK : 14332

Upon adding the following code and executing 
```
var graphicsEffect = new ArithmeticCompositeEffect
{
    Name = "Arithmetic",
    Source1 = new CompositionEffectSourceParameter("ImageSource"),
    Source1Amount = .1f,
    Source2 = new Transform2DEffect
    {
        Name = "LightMapTransform",
        Source = new CompositionEffectSourceParameter("LightMap")
    },
    Source2Amount = 0,
    MultiplyAmount = 1
};

var _effectFactory = compositor.CreateEffectFactory(graphicsEffect, new[] { "LightMapTransform.TransformMatrix" });
```

I am getting the following exception

```
An exception of type 'System.TypeLoadException' occurred in CompositionExpressionToolkitClient.exe and wasn't handled before a managed/native boundary

Additional information: Requested Windows Runtime type 'Microsoft.Graphics.Canvas.Effects.ArithmeticCompositeEffect' is not registered.
"Requested Windows Runtime type 'Microsoft.Graphics.Canvas.Effects.ArithmeticCompositeEffect' is not registered.":"Microsoft.Graphics.Canvas.Effects.ArithmeticCompositeEffect"
```

**InnerException:**
```
Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
```

I have added a reference to **win2d.uwp** to my project.

**Comment by pgills** [comment] 2016-05-09 15:30
@ratishphilip Thanks for the good repo information. 

Also, what version of Win2D.uwp are you using? The latest I assume?

**Comment by ratishphilip** [comment] 2016-05-09 16:18
Yes I am using the latest version (1.17.0)

**Comment by krenner** [comment] 2016-05-12 02:39
@ratishphilip Thanks for commenting on this exception. I'm not able to reproduce this using Win2D UWP 1.17.0 and the effect description you have above.  Have you had success with effects and Win2D prior to this?

**Comment by ratishphilip** [comment] 2016-05-12 04:16
@krenner Yes, I had success with effects and Win2D prior to this. I have successfully compiled and executed the Win2D gallery samples.

Now I have updated to Build 14342 and I am **not** seeing this exception now. I am not sure whether the issue was with the previous build of Windows.

**Comment by krenner** [comment] 2016-05-14 01:59
@ratishphilip  Glad to hear this is no longer an issue for you.  I'll close this out but please let us know if you run into this problem again.

**Closed by krenner** 2016-05-14 01:59 UTC
Labels: bug
